name: cmad
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11,<3.14
  - numpy>=1.23
  - matplotlib
  - scipy>=1.7
  - jupyter
  - pytest
  - coverage>=6.4
  - pytest-cov
  - mypy
  - ruff
  - pip
  - setuptools
  - scikit-learn
  - sympy
  - jsonschema
  - pyyaml
  - pip:
    - jax[cpu]>=0.4.20
